### PR TITLE
Adds the URL to terminal output

### PR DESCRIPTION
**Pull request by ngbravo**
Solves https://github.com/shoreditch-ops/artillery/issues/221 by adding the URL as an option when calling printReport. 

This does **not** add the url to the report itself, just to the print.

Question: why is the URL not in the report itself?

### CODE REVIEW

**Comment by hassy** [comment]
Thanks @ngbravo. I don't think this will work if we have any environments specified (via `config.environments`) though.

**Comment by ngbravo** [comment]
You're right. I have a couple of questions before moving forward:: 

1. Considering there seems to be no restriction on name or amount of environments, which should be printed out?
2. Is my approach of have the URL printed out, but not in the report itself, ok for you?

Cheers!

**Comment by hassy** [comment]
The user would expect the URL that the tests are running against to be printed. It's fine to only print the target in the console.

**Comment by ngbravo** [comment]
@hassy Now it should work when there is an environment stated, else it defaults to the specified global target.

**Comment by hassy** [comment]
Closing for now as it needs a rebase. Happy to merge if/when fixed though.

**Comment by ngbravo** [comment]
I genuinely wanted to contribute and help maintain artillery, but taking 2 months to approve, and then rejecting the PR because it needs a rebase (no surprise) is quite disrespectful.

I will no longer use, recommend, or try to contribute to this project.

**Comment by hassy** [comment]
I appreciate that and thanks for your time. Not that you probably care at this point, but maintaining a free open source project is a big time investment, and PRs can and do fall by the wayside unless critical and/or the contributor is active.

**Pull request closed without merging**
